GET http://localhost:3001/videos/

###
GET http://localhost:3001/video/2

###
POST http://localhost:3001/video
Content-Type: application/json

{
   "url": "http://local:3001/youtube/video",
   "title": "testing video",
   "description": "first video"
}

###
PUT http://localhost:3001/video/3

###
DELETE http://localhost:3001/video/4
